services:
  backend:
    build:
      context: ./backend
    expose:
      - 8000
    volumes:
      - ./backend/database/data:/app/data

  frontend:
    build:
      context: ./frontend/web
    ports:
      - 80:80
    volumes:
      - ./nginx/dev_nginx.conf:/etc/nginx/nginx.conf